language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  ssh_known_hosts: conjars.org
before_install:
- openssl aes-256-cbc -K $encrypted_a6ea9de684b4_key -iv $encrypted_a6ea9de684b4_iv
  -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: gradlew deploy
  on:
    branch: /^release.*$/
